
help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  ica           use ICA to remove eye blinks and heart beat"
	@echo "  epochs        create epochs and evoked responses"
	@echo "  all           all processing "
	@echo "  clean	remove intermediate scripts generated by processing"

SUBJ := $(shell cat subjects.txt)

sensor: ica epochs noise_cov
source: forward inverse
all: ica epochs noise_cov forward inverse

tsss:
	for i in $(SUBJ); do \
		python tsss.py $$i -ses 01 -task audvis -run 01; \
		python tsss.py $$i -ses 01 -task audvis -run 02; \
		python tsss.py $$i -ses 02 -task audvis -run 01; \
		python tsss.py $$i -ses 02 -task audvis -run 02; \
	done

ica:
	for i in $(SUBJ); do \
		python ica.py $$i;\
	done

epochs:
	for i in $(SUBJ); do \
        python epochs.py $$i -ses 01 -task audvis;\
        python epochs.py $$i -ses 02 -task audvis;\
	done

noise_cov: 
	for i in $(SUBJ); do \
		python noise_cov.py $$i -ses 01;\
		python noise_cov.py $$i -ses 02;\
	done	

forward: 
	for i in $(SUBJ); do \
		python forward.py $$i;\
	done

inverse:
	for i in $(SUBJ); do \
		python inverse.py $$i -ses 01 -task audvis;\
		python inverse.py $$i -ses 02 -task audvis;\
	done

