
help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  ica           xxx"
	@echo "  source       xxx"
	@echo "  all           all processing "
	@echo "  clean	remove intermediate scripts generated by processing"

SUBJ := $(shell cat subject_text_files/test.txt)

sensor: ica annot noise_cov
source: coreg forward inverse 
all: ica annot noise_cov coreg forward inverse extract


ica:
	for i in $(SUBJ); do \
		python make_ica.py $$i;\
	done
	
annot:
	for i in $(SUBJ); do \
		python make_annotations.py $$i;\
	done
	
coreg:
	for i in $(SUBJ); do \
		python coregistration.py $$i;\
	done


noise_cov: 
	for i in $(SUBJ); do \
		python 01_covariance.py $$i -ses 01;\
		python 01_covariance.py $$i -ses 02;\
	done	

forward: 
	for i in $(SUBJ); do \
		python 02_forward.py $$i;\
	done

inverse:
	for i in $(SUBJ); do \
		python 03_inverse.py $$i -ses 01 -task audvis;\
		python 03_inverse.py $$i -ses 02 -task audvis;\
	done

extract:
	for i in $(SUBJ); do \
		python 04_extract_npyfile.py $$i;\
	done
